// src/mockData/freightForwarders.js
export const mockFreightForwarders = [
    {
      id: 1,
      name: "Global Logistics Co.",
      logo: "https://logo.clearbit.com/globallogistics.com",
      employees: 150,
      status: "active",
      rating: 4.7,
      ordersCompleted: 1250,
      isVerified: true,
      services: ["air", "sea", "rail"],
    },
    {
      id: 2,
      name: "Swift Shipping Solutions",
      logo: "https://logo.clearbit.com/maersk.com",
      employees: 75,
      status: "active",
      rating: 4.2,
      ordersCompleted: 830,
      isVerified: true,
      services: ["sea", "road"],
    },
    {
      id: 3,
      name: "AirFreight Express",
      logo: "https://logo.clearbit.com/dhl.com",
      employees: 100,
      status: "inactive",
      rating: 3.9,
      ordersCompleted: 620,
      isVerified: false,
      services: ["air"],
    },
    {
      id: 4,
      name: "OceanWide Logistics",
      logo: "https://logo.clearbit.com/oceanwidelogistics.com",
      employees: 200,
      status: "active",
      rating: 4.5,
      ordersCompleted: 1500,
      isVerified: true,
      services: ["sea", "rail"],
    },
    {
      id: 5,
      name: "BlackListed Freight",
      logo: "https://logo.clearbit.com/easyship.com",
      employees: 50,
      status: "blacklisted",
      rating: 2.1,
      ordersCompleted: 300,
      isVerified: false,
      services: ["air", "sea"],
    },
    {
      id: 6,
      name: "EcoShip Logistics",
      logo: "https://logo.clearbit.com/hemas.com",
      employees: 120,
      status: "active",
      rating: 4.8,
      ordersCompleted: 980,
      isVerified: true,
      services: ["sea", "road", "rail"],
    },
    {
      id: 7,
      name: "RapidAir Cargo",
      logo: "https://logo.clearbit.com/flexport.com",
      employees: 80,
      status: "active",
      rating: 4.3,
      ordersCompleted: 750,
      isVerified: true,
      services: ["air"],
    },
    {
      id: 8,
      name: "GlobalRail Connect",
      logo: "https://logo.clearbit.com/searates.com",
      employees: 90,
      status: "inactive",
      rating: 3.7,
      ordersCompleted: 520,
      isVerified: false,
      services: ["rail", "road"],
    },
    {
      id: 9,
      name: "SeaWave Shipping",
      logo: "https://logo.clearbit.com/oocl.com",
      employees: 180,
      status: "active",
      rating: 4.6,
      ordersCompleted: 1350,
      isVerified: true,
      services: ["sea"],
    },
    {
      id: 10,
      name: "AllRoads Transport",
      logo: "https://logo.clearbit.com/allroadstransport.com",
      employees: 65,
      status: "active",
      rating: 4.0,
      ordersCompleted: 600,
      isVerified: true,
      services: ["road"],
    }
  ];